export const START = 'CPT_GAME_START'
export const CONTINUE = 'CPT_GAME_CONTINUE'
export const SQUARE_ROTATE = 'CPT_SQUARE_ROTATE'
export const MOVE_LEFT = 'CPT_MOVE_LEFT'
export const MOVE_RIGHT = 'CPT_MOVE_RIGHT'
export const MOVE_DOWN = 'CPT_MOVE_DOWN'
export const FALL_DOWN = 'CPT_FALL_DOWN'
export const FIX_SQUARE = 'CPT_FIX_SQUARE'
export const NEXT = 'CPT_NEXT'
export const CLEAN_LINE = 'CPT_CLEAN_LINE'
export const ADD_LINE = 'CPT_ADD_LINE'
export const SET_TIME = 'CPT_SET_TIME'
export const GAME_OVER = 'CPT_GAME_OVER'

export const GUEST_CHANGE = 'CPT_GUEST_CHANGE'
export const CHANGE = 'CPT_CHANGE'
